Repository SEOULMILK4/SEOULMILK_BE, pull requests merged in 2025-02, with the labels that each got.

#3 [Feat] swagger 및 baseEntity 초기 설정
  build.gradle
  src/main/java/com/seoulmilk/seoulmilkServer/global/common/BaseEntity.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/SecurityConfig.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/SwaggerConfig.java
Labels: 💻 feature, 📌 setting

#4 #1 feat : common exception 구현
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorResponse.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/GlobalExceptionHandler.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/exception/BusinessException.java
Labels: 💻 feature, 📌 setting

#7 [Feat] member 로그인 + 이메일 인증 구현
  build.gradle
  src/main/java/com/seoulmilk/seoulmilkServer/SeoulmilkServerApplication.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/controller/AuthController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/controller/AuthPasswordController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/domain/AuthVerifiedMember.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/domain/RefreshTokenEntity.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/CreateOtpRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/CreateOtpResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/GetLoginRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/GetLoginResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/GetNewTokenResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/PostVerifyOtpRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/PostVerifyOtpResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/UpdatePasswordRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/dto/UpdatePasswordResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/repository/AuthVerifyRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/service/AuthService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/service/AuthVerifyService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/auth/service/RefreshTokenService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/domain/Member.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/domain/Role.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/repository/MemberRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/common/ApiResponse.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/EmailConfig.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/RedisConfig.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/SecurityConfig.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorResponse.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/GlobalExceptionHandler.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/jwt/properties/JwtProperties.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/jwt/provider/JwtProvider.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/mail/properties/EmailProperties.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/mail/service/EmailService.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/mail/service/OTPService.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/security/CustomUserDetails.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/security/CustomUserDetailsService.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/security/SecurityUtils.java
  src/main/resources/templates/email-template.html
Labels: 💻 feature, 📌 setting

#9 [Feat] dockerfile 작성
  src/Dockerfile
Labels: 🌎 deploy, 📌 setting

#10 [Feat] : dockerfile 위치 변경
  Dockerfile
Labels: 🛠️ refactor, 📌 setting

#11 [Feat] : 포트 지정
  Dockerfile
Labels: 🌎 deploy, 📌 setting

#13 [Feat] : redis 비밀번호 설정
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/RedisConfig.java
Labels: 💻 feature, 📌 setting

#15 [Feat] : webconfig 추가
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/WebConfig.java
Labels: 💻 feature, 📌 setting
