Repository SEOULMILK4/SEOULMILK_BE, pull requests merged in 2025-03, with the labels that each got.

#17 [Feat] 세금계산서 도메인 생성 + OCR 구현
  build.gradle
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/OcrController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/ARAP.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/ClovaOcr.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrExtractor.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
Labels: 💻 feature

#21 [Feat] : 프론트 배포 도메인 추가
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/WebConfig.java
Labels: 💻 feature, 🌎 deploy

#29 [Bugfix] ntsTaxResponse에 Status 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrParser.java
Labels: ❌ bug

#30 [Feat] 홈택스 진위 여부 판별 api 구현
  build.gradle
  src/main/java/com/seoulmilk/seoulmilkServer/SeoulmilkServerApplication.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/OcrTaxInvoiceRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/OcrTaxInvoiceResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/HomeTaxService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/HomeTaxServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/codef/domain/CodefAccessToken.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/codef/properties/CodefProperties.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/codef/repository/CodefTokenRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/codef/service/CodefAuthService.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
Labels: 💻 feature

#37 [Feat] 사원대리점 등록 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/SeoulmilkServerApplication.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminAgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminAuthController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminEmployeeController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/GetAgencyResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/GetEmployeeWithAgencyResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/InviteAgenciesRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/PostAdminRegisterAgencyRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/PostAdminRegisterAgencyResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/UpdateAgencyRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/UpdateAgencyResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/auth/PostAdminLoginRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/auth/PostAdminLoginResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/GetOneEmployeeResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/PostEmployeeRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/PostEmployeeResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminAgencyService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminAuthService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminEmployeeService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyAuthController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/domain/Agency.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/dto/etc/ChangeAgencyPasswordRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/repository/AgencyRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/service/AgencyAuthService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberAuthController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/domain/Member.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/dto/auth/ChangeMemberPasswordRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/repository/MemberRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/service/MemberAuthService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/SecurityConfig.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/etc/MemberProperties.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/mail/service/EmailService.java
  src/main/resources/templates/agency-invitation-template.html
Labels: 💻 feature, 🛠️ refactor

#42 [Feat] : dto 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/dto/login/GetAgencyLoginResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/dto/auth/GetLoginResponseDTO.java
Labels: 🛠️ refactor

#44 [Feat] 목록 조회 response 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxListResponseDTO.java
Labels: 💻 feature

#45 [Feat] 세금 계산서 response 원본 파일 이름 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrParser.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxCommandServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/OcrServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/service/S3Service.java
Labels: 💻 feature

#46 [Feat] 홈택스 검증 제출 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/OcrTaxInvoiceRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/SubmitNtxTaxRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/OcrTaxInvoiceResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/HomeTaxServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtxTaxMappingService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtxTaxMappingServiceImpl.java
Labels: 💻 feature, 🛠️ refactor

#48 [Refactor] webconfig 수정
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/WebConfig.java
Labels: 🛠️ refactor

#50 [Refactor] : dto수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/dto/login/GetAgencyLoginResponseDTO.java
Labels: 🛠️ refactor

#54 [Fix] 컨테이너 재실행 위해 재배포
  Dockerfile
Labels: ❌ bug

#59 [Refactor] 세금 계산서 목록 조회 API 성공 여부 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxListResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/UpdateNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxCommandService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxCommandServiceImpl.java
Labels: 🛠️ refactor

#62 [Feat] 사원 - 개별 세금계산서 조회, 수정, 재검증 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/service/MemberService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/ModifyNtsTaxRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/ModifyNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOneNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
Labels: 💻 feature

#64 [Feat] 세금 계산서 검증 결과 일괄 조회 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetHometaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxListResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/error/ErrorCode.java
Labels: 💻 feature

#68 [Refactor] : 스웨거 분류 작업
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
Labels: 🛠️ refactor

#71 [Feat] : 이미지 다운로드 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/global/service/S3Downloader.java
Labels: 💻 feature

#72 [Refactor] 대리점 세금 계산서 수정, 삭제 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/controller/NtsTaxController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/DeleteNtsTaxRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/UpdateNtsTaxRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxCommandService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxCommandServiceImpl.java
Labels: 💻 feature, 🛠️ refactor

#75 [Feat] : 세금계산서 제출 결과 조회 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 💻 feature

#76 [Refactor] : 목록 조회 api 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 🛠️ refactor

#78 [Feat] : suName, ipName 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/domain/NtsTax.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/ModifyNtsTaxRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/ModifyNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 🛠️ refactor

#79 [Feat] csv 추출 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetHometaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 💻 feature

#85 [Refactor] ocr response 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: ❌ bug, 🛠️ refactor

#87 [Refactor] : 세금계산서 목록 조회 api - 공백 제거
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxListResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
Labels: 🛠️ refactor

#89 [Bugfix] 세금 계산서 목록 조회 API 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: ❌ bug

#92 [Bugfix] 본사 - 세금 계산서 목록 조회 API 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: ❌ bug

#94 [Feat] 관리자 세금계산서 통합조회 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 💻 feature

#98 [Bugfix] 본사 - 세금 계산서 검색 API 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: ❌ bug

#100 [Bugfix] 본사 - 세금 계산서 검색 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
Labels: ❌ bug

#104 [Refactor] : 일치 불일치 건수 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetNtsTaxListResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 🛠️ refactor

#105 [Feat] 관리자 - csv 추출 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepositoryImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 💻 feature

#110 [Refactor] : 관리자 csv 추출 api - 파라미터 name 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
Labels: 🛠️ refactor

#115 [Feat] : webconfig수정
  src/main/java/com/seoulmilk/seoulmilkServer/global/config/WebConfig.java
Labels: 💻 feature

#113 [Feat] : 관리자 csv idlist로 추출 api 구현
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/request/GetCsvRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 💻 feature

#119 [Refactor] csv dto 필드 순서 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetCsvResponseDTO.java
Labels: 🛠️ refactor

#122 [Feat] 본사 - 선택한 세금 계산서 CSV 추출 API
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrParser.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/OcrServiceImpl.java
Labels: 💻 feature, 🛠️ refactor

#126 [Refactor] : 관리자 - 대리점 목록 조회 승인 상태 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/GetAgencyListWithStatusResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/GetAgencyResponseDTO.java
Labels: 🛠️ refactor

#128 [Feat] : 사원 개별 정보 조회 - 담당 대리점 목록도 반환하게 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/GetOneAgencyByEmployeeResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/GetOneEmployeeResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminEmployeeService.java
Labels: 💻 feature

#130 [Refactor] : 세금계산서 제출 api - success인것으로 제한하는 조건 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtxTaxMappingServiceImpl.java
Labels: 🛠️ refactor

#133 [Refactor] : 조회조건 파라미터 이름 통일
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/controller/AgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
Labels: 🛠️ refactor

#135 [Refactor] : 토큰 로그 출력문 제거
  src/main/java/com/seoulmilk/seoulmilkServer/global/jwt/provider/JwtProvider.java
Labels: 🛠️ refactor

#136 [Refactor] ocr 정확도 리팩토링
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrParser.java
Labels: 🛠️ refactor

#138 [Refactor] : 메일 - 회원가입링크 수정
  src/main/resources/templates/agency-invitation-template.html
Labels: 🛠️ refactor

#141 [Refactor] 본사 - 세금 계산서 검색 API 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
Labels: 🛠️ refactor

#145 [Refactor] status controller 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/member/controller/MemberController.java
Labels: 🛠️ refactor

#147 [Refactor] : 관리자 목록 조회 - 홈택스 검증 거친것만 보내주도록 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/repository/NtsTaxRepository.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/NtsTaxQueryServiceImpl.java
Labels: 🛠️ refactor

#148 [Refactor] OCR 리팩토링
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/ocr/OcrParser.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/service/OcrServiceImpl.java
Labels: 🛠️ refactor

#153 [Feat] 담당 대리점 배정 api 추가
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminEmployeeController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/employee/PostAssignAgeciesRequestDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminEmployeeService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/domain/Agency.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/repository/AgencyRepository.java
Labels: 💻 feature

#157 [Bugfix] 세금 계산서 수정 시, 날짜 수정 불가능
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/UpdateNtsTaxResponseDTO.java
Labels: 🛠️ refactor

#159 [Refactor] : 대리점 목록 조회 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/controller/AdminAgencyController.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/dto/agency/GetAgencyResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminAgencyService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/repository/AgencyRepository.java
Labels: 🛠️ refactor

#160 [Refactor] response 날짜 응답값 변경
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/GetOcrNtsTaxResponseDTO.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/ntsTax/dto/response/UpdateNtsTaxResponseDTO.java
Labels: 🛠️ refactor

#162 [Refactor] : 미가입만 반환하게 수정
  src/main/java/com/seoulmilk/seoulmilkServer/domain/admin/service/AdminAgencyService.java
  src/main/java/com/seoulmilk/seoulmilkServer/domain/agency/repository/AgencyRepository.java
Labels: 🛠️ refactor
